# Generated by Django 5.1.4 on 2024-12-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/resumes'),
        ),
    ]
